services:
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: greenguard
      POSTGRES_PASSWORD: greenguard
      POSTGRES_DB: greenguard
    ports:
      - "5432:5432"
    networks:
      - greenguard
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "greenguard"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  greenguard-web:
    container_name: greenguard-web
    image: ghcr.io/greenguard-dev/greenguard-web:latest
    ports:
      - 8080:8080
    environment:
      - ConnectionStrings__DefaultConnection=Host=greenguard;Port=5432;Database=greenguard;Username=greenguard;Password=greenguard
    restart: always
    networks:
      - greenguard
    depends_on:
      postgres:
        condition: service_healthy
networks:
  greenguard:
    driver: bridge