on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: sillyangel/releases-to-discord@v1.0.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}